services:
  internal-uploader:
    build:
      context: https://github.com/niroselania/upload.git#main
      dockerfile: Dockerfile
    container_name: internal-uploader
    ports:
      - "3020:3000"
    volumes:
      - /ZimaOS-HD/Downloads:/uploads
    environment:
      PORT: "3000"
      PUBLIC_BASE_PATH: "/modules/icewhale_files"
      PUBLIC_URL: "http://patagonia.serveftp.com/modules/icewhale_files/#/files/HDD-500/UPLOAD%20EXT"
      TARGET_MODE: "local"
      UPLOAD_DIR: "/uploads"
      UPLOAD_USER: "niros"
      UPLOAD_PASS: "ardy30fe"
      TARGET_URL: "http://patagonia.serveftp.com/modules/icewhale_files/#/files/HDD-500/UPLOAD%20EXT"
      MAX_FILE_SIZE_MB: "5120"
    restart: unless-stopped
