services:
  internal-uploader:
    build: .
    container_name: internal-uploader
    ports:
      - "3020:3000"
    environment:
      PORT: "3000"
      PUBLIC_BASE_PATH: "/modules/icewhale_files"
      PUBLIC_URL: "http://patagonia.serveftp.com/modules/icewhale_files/#/files/HDD-500/UPLOAD%20EXT"
      TARGET_MODE: "webdav"
      TARGET_URL: "http://patagonia.serveftp.com/modules/icewhale_files/#/files/HDD-500/UPLOAD%20EXT"
      MAX_FILE_SIZE_MB: "5120"
    restart: unless-stopped
